const players = [
	{
		alias: 'PrinzCL',
		name: 'Maximiliano',
		team: 'Blackout Esports',
		game: 'Valorant',
		role: 'Duelista',
		country: 'CL',
		mouse: 'Viper V3 Pro',
		keyboard: 'Wooting 80HE',
		headset: 'Cloud III Wireless',
		monitor: 'ZOWIE XL2566K',
		sensitivity: '0.32 @ 800 DPI',
		peripherals: [
			{ type: 'Mouse', name: 'Viper V3 Pro', specs: '54 g · 35K DPI · inalámbrico', search: 'Razer Viper V3 Pro' },
			{ type: 'Teclado', name: 'Wooting 80HE', specs: 'Rapid Trigger · switches Lekker', search: 'Wooting 80HE' },
			{ type: 'Headset', name: 'Cloud III Wireless', specs: 'Audio espacial · 120 h de batería', search: 'HyperX Cloud III Wireless' },
			{ type: 'Monitor', name: 'ZOWIE XL2566K', specs: '24.5 pulgadas · 360 Hz · DyAc+', search: 'ZOWIE XL2566K' },
		],
	},
	{
		alias: 'feehhh',
		name: 'Fernando',
		team: 'Blackout Esports',
		game: 'Valorant',
		role: 'Iniciador',
		country: 'CL',
		mouse: 'DeathAdder V3 Pro',
		keyboard: 'G Pro X TKL',
		headset: 'Arctis Nova Pro',
		monitor: 'ZOWIE XL2546K',
		sensitivity: '1.45 @ 400 DPI',
		peripherals: [
			{ type: 'Mouse', name: 'DeathAdder V3 Pro', specs: '63 g · 30K DPI · inalámbrico', search: 'Razer DeathAdder V3 Pro' },
			{ type: 'Teclado', name: 'G Pro X TKL', specs: 'Tenkeyless · switches GX', search: 'Logitech G Pro X TKL' },
			{ type: 'Headset', name: 'Arctis Nova Pro', specs: 'ANC · estación inalámbrica', search: 'SteelSeries Arctis Nova Pro Wireless' },
			{ type: 'Monitor', name: 'ZOWIE XL2546K', specs: '24.5 pulgadas · 240 Hz · DyAc+', search: 'ZOWIE XL2546K' },
		],
	},
	{
		alias: 'Moi',
		name: 'Alonso',
		team: 'Blackout Academy',
		game: 'Valorant',
		role: 'Duelista',
		country: 'CL',
		mouse: 'EC2-CW',
		keyboard: 'Huntsman V3 Pro',
		headset: 'BlackShark V2 Pro',
		monitor: 'Alienware AW2524H',
		sensitivity: '0.25 @ 800 DPI',
		peripherals: [
			{ type: 'Mouse', name: 'EC2-CW', specs: '77 g · sensor 3370 · inalámbrico', search: 'ZOWIE EC2-CW' },
			{ type: 'Teclado', name: 'Huntsman V3 Pro', specs: 'Rapid Trigger · switches ópticos', search: 'Razer Huntsman V3 Pro' },
			{ type: 'Headset', name: 'BlackShark V2 Pro', specs: 'Audio espacial · 70 h de batería', search: 'Razer BlackShark V2 Pro' },
			{ type: 'Monitor', name: 'Alienware AW2524H', specs: '24.5 pulgadas · 500 Hz · IPS', search: 'Alienware AW2524H' },
		],
	},
	{
		alias: 'Luma',
		name: 'Lucía',
		team: 'Blackout Game Changers',
		game: 'Valorant',
		role: 'Controladora',
		country: 'ES',
		mouse: 'EC2-CW',
		keyboard: 'Huntsman V3 Pro',
		headset: 'BlackShark V2 Pro',
		monitor: 'Alienware AW2524H',
		sensitivity: '0.25 @ 800 DPI',
		peripherals: [
			{ type: 'Mouse', name: 'EC2-CW', specs: '77 g · sensor 3370 · inalámbrico', search: 'ZOWIE EC2-CW' },
			{ type: 'Teclado', name: 'Huntsman V3 Pro', specs: 'Rapid Trigger · switches ópticos', search: 'Razer Huntsman V3 Pro' },
			{ type: 'Headset', name: 'BlackShark V2 Pro', specs: 'Audio espacial · 70 h de batería', search: 'Razer BlackShark V2 Pro' },
			{ type: 'Monitor', name: 'Alienware AW2524H', specs: '24.5 pulgadas · 500 Hz · IPS', search: 'Alienware AW2524H' },
		],
	},
    {
    alias: 'DaikoVlr',
    name: 'Matias',
    team: 'Blackout Esports',
    game: 'Valorant',
    role: 'Flex',
    country: 'CL',
    mouse: 'Razer Viper V3 Pro',
    keyboard: 'Razer Huntsman mini',
    headset: 'Logitech G435',
    monitor: 'MasterG',
    sensitivity: '0.32 @ 800 DPI',
    peripherals: [
      { type: 'Mouse', name: 'DeathAdder V3 Pro', specs: '63 g · 30K DPI · inalámbrico', search: 'Razer DeathAdder V3 Pro' },
      { type: 'Teclado', name: 'G Pro X TKL', specs: 'Tenkeyless · switches GX', search: 'Logitech G Pro X TKL' },
      { type: 'Headset', name: 'Arctis Nova Pro', specs: 'ANC · estación inalámbrica', search: 'SteelSeries Arctis Nova Pro Wireless' },
      { type: 'Monitor', name: 'ZOWIE XL2546K', specs: '24.5 pulgadas · 240 Hz · DyAc+', search: 'ZOWIE XL2546K' },
    ],
    game: 'Valorant',
    role: 'Controlador',
    country: 'CL',
    mouse: 'EC2-CW',
    keyboard: 'Huntsman V3 Pro',
    headset: 'BlackShark V2 Pro',
    monitor: 'Alienware AW2524H',
    sensitivity: '0.25 @ 800 DPI',
    peripherals: [
      { type: 'Mouse', name: 'EC2-CW', specs: '77 g · sensor 3370 · inalámbrico', search: 'ZOWIE EC2-CW' },
      { type: 'Teclado', name: 'Huntsman V3 Pro', specs: 'Rapid Trigger · switches ópticos', search: 'Razer Huntsman V3 Pro' },
      { type: 'Headset', name: 'BlackShark V2 Pro', specs: 'Audio espacial · 70 h de batería', search: 'Razer BlackShark V2 Pro' },
      { type: 'Monitor', name: 'Alienware AW2524H', specs: '24.5 pulgadas · 500 Hz · IPS', search: 'Alienware AW2524H' },
    ],
  },
]

export default players
